# Generated by Django 4.2.17 on 2025-12-18 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniRecordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del mini recordatorio', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional')),
                ('hora', models.TimeField(help_text='Hora del recordatorio')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_recordatorios', to='web.usuario')),
            ],
            options={
                'verbose_name': 'Mini Recordatorio',
                'verbose_name_plural': 'Mini Recordatorios',
                'db_table': 'mini_recordatorios',
                'ordering': ['hora'],
            },
        ),
    ]
